### ISSUE TITLE
Memory allocation bug when linking to debug version of the library

### ISSUE THREAD

**Issue by leledumbo** [dliw/fpCEF3#11]
When I link to Debug version of libcef.so (and libffmpegsumo.so), LCLSimple example outputs:

> $ ./simple 
> [0105/221603:ERROR:audio_manager_pulse.cc(250)] Failed to connect to the context.  Error: Connection refused
> memory allocation bug: object at 0x1640ec0 has never been allocated
> Segmentation fault (core dumped)
> [0105/221604:FATAL:sys_info_linux.cc(47)] Check failed: limit > 0. 
>  [0x7f963229d4dc] base::debug::StackTrace::StackTrace()
>  [0x7f96323051ef] logging::LogMessage::~LogMessage()
>  [0x7f96323b9baf] (anonymous namespace)::MaxSharedMemorySize()
>  [0x7f96323ba321] base::internal::LazySysInfoValue<>::LazySysInfoValue()
>  [0x7f96323ba2e4] base::DefaultLazyInstanceTraits<>::New()
>  [0x7f96323ba102] base::internal::LeakyLazyInstanceTraits<>::New()
>  [0x7f96323ba073] base::LazyInstance<>::Pointer()
>  [0x7f96323b9f5a] base::LazyInstance<>::Get()
>  [0x7f96323b9c14] base::SysInfo::MaxSharedMemorySize()
>  [0x7f9632b4be24] content::PreSandboxInit()
>  [0x7f9632b4bf15] content::EnterSuidSandbox()
>  [0x7f9632b4c55f] content::ZygoteMain()
>  [0x7f963708e87d] content::RunZygote()
>  [0x7f963708ed4f] content::RunNamedProcessTypeMain()
>  [0x7f963708fe85] content::ContentMainRunnerImpl::Run()
>  [0x7f963708e11b] content::ContentMain()
>  [0x7f96320b50df] CefExecuteProcess()
>  [0x7f9631fdf381] cef_execute_process
>  [0x000000724732] CEF3LIB_$$_CEFINITIALIZE$crc97D6A61A
> 
> memory allocation bug: object at 0x210fed0 has never been allocated

**Comment by dliw** [comment]
Sorry for this late response, somehow missed that one...

It very much looks like the issue I have with openSUSE...
Did you try

>If you're using openSUSE (maybe some other distros, too) and your program crashes immidiately >after being started, you could try to execute

>echo 1073741824 > /proc/sys/kernel/shmmax

>and see if the crash goes away.

? (Hint section in the Readme)

Unfortunately I'm very busy - again - atm, so if that's another issue, I can't help you right now.
CEF 3.2171 got released just few days ago and I hope to provide an update for fpCEF by the end of February.

**Comment by dliw** [comment]
CEF uses tcmalloc which causes problems when used within a library. The provided builds for CEF 3.1750 used to work most of the time, but it is better to use a Linux build of CEF with tcmalloc disabled.
