### ISSUE TITLE
CEF 3.2171.1979 not supported

### ISSUE THREAD

**Issue by mohsenti** [dliw/fpCEF3#13]
Hi
I try to run GT2Minimal Example with lazarus 1.4.0 and freepascal 2.6.4 on ubuntu 14.04 and cef library version 3.2171.1979 but after application run a "Unsupported CEF library version " exception raised.

**Comment by dliw** [comment]
The exception is correct. The latest supported version is 3.1750...

I did not push the update to 3.2171, as I found no way to make it work on Linux...
See [here](http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12675) or [here](https://bitbucket.org/chromiumembedded/cef/issue/1545) for information about the problem...
