### ISSUE TITLE
make examples execute in my environment

### ISSUE THREAD

**Issue by malcome** [dliw/fpCEF3#16]
Following code is needed to make examples execute in my environment.

Code:
//Add to TMainform.FormCreate
CefResourcesDirPath:='Resources';
CefLocalesDirPath:='Resources\locales';
CefInitDefault;

My Environment:
Windows7 32bit
Lazarus 1.4.4
CEF 3.1750
I am using fpCEF for CEF 3.1750. Because new for 3.2454 can not run in my environment. ;-(

Thank you so much for your great work.

**Comment by dliw** [comment]
The internals of CEF changed, I can't do anything about this. Apart from that, CEF expects all paths to be *absolute*, although relative paths used to work in the past sometimes.

It should still be possible to put the resources in a different folder, see [here](http://wiki.freepascal.org/fpCEF3). Only the file `icudtl.dat` has to be in the same folder as the exe.

**Comment by malcome** [comment]
Hi dliw.
New CEF3.2454 works as I set CefResourcesDirPath and CefLocalesDirPath with absolute path, and moved icudtl.dat file.
Thank you for your help!
