### ISSUE TITLE
Is string type correct?

### ISSUE THREAD

**Issue by malcome** [dliw/fpCEF3#17]
TChromiumFontOptions.StandardFontFamily, FixedFontFamily or etc is type of String.
The correct type is not String but ustring?
(Or need using UTF8Decode in GetFontFamily and SetFontFamily method.)
many "Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString" " is up in Lazarus trunc with FPC3.0.0RC2.

**Comment by dliw** [comment]
It must be **String**, otherwise one couldn't change the value in the object inspector.

From the many fonts I have, not a single one contains non-ascii characters, but probably it would be better to use the `UFT8*` functions for conversion anyway.
