### ISSUE TITLE
multi tab browser

### ISSUE THREAD

**Issue by mercurylmy** [dliw/fpCEF3#18]
Please add a simple multi tab browser example.
What QtWebKit have. http://users.telenet.be/Jan.Van.hijfte/qtforfpc/fpcqt4.html (at the bottom)
Using TPageControl. LCL doesn’t support nboShowCloseButtons which QT does, but it doesn't matter. I just want multi tab.
And also cookies, proxy, authentication, flash......
Thank you very much.

**Comment by dliw** [comment]
fpCEF is only a wrapper, if you need a fully featured browser, it's up to you to implement it.

For tabbed browsing you have to create TChromium at runtime for each tab in TPageControl, just like you would do for e.g. a tabbed text editor.

**Comment by mercurylmy** [comment]
Well, I even don't know how to start. Please give me some help. Should I create 1 Chromium process for all tabs or 1 tab 1 process. And how to hook open window event to show the new page in a tab instead window. And how to read or write the cookies to a file or memory. Could you please port TWebPanel to fpCEF3?
Thank you very much.

**Comment by dliw** [comment]
Ok, I see. I will try to port TWebPanel, but it will take a while.

If you want to try yourself, just imagine TChromium to be a TButton. You need a new instance of TChromium for every new tab. CEF itself has no idea of tabs.

For hooking the open window event the CefLiveSpanHandler - see [here](http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefLifeSpanHandler.html) - could be used I think.

Cookies are managed by CEF, you can access them via the CookieManager, see  [here](http://magpcss.org/ceforum/apidocs/projects/%28default%29/CefCookieManager.html)
If you set a storage path, cookies are written to disk, otherwise they are only kept in memory. 

The whole available CEF API and the description of each function can be found in `cef3api.pas`.

**Comment by zbyna** [comment]
For tab implementation this could be important too:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=4703
https://code.google.com/p/chromiumembedded/issues/detail?can=2&q=1526&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&id=1526

**Comment by dliw** [comment]
I just pushed a new example, that shows how to create a tabbed browser. It also shows how to access the cookies via the cookie manager.

Cookies are managed by CEF itself and saved to disk, if a `CefCachePath` is set.  Please see `cef3.api` (_TCefCookieManager_) for information on how to use the cookie manager.

For proxy you have to use a command line switch like `--proxy-server=socks5://127.0.0.1:8888`.
You can append this switch by using the callback `CefOnBeforeCommandLineProcessing`, see [here](http://www.magpcss.org/ceforum/viewtopic.php?f=14&t=11717).

Plugins can by enabled via the `Chromium.Options.Plugins` switch. For Flash you need to have _pepperflash_ installed and set up correctly (should be the case if you have Chrome installed on your system).

**Comment by mercurylmy** [comment]
Not working for me. 
![2015-12-15_102649](https://cloud.githubusercontent.com/assets/8626952/11800386/e99bf160-a316-11e5-8d52-79d6f20e7bea.jpg)
```<a href="xxx.html" target="_blank">xxx</a>``` still open a new window.
And seems doesn’t compatible with fpCEF3-3.1750. 

This is the page in IE.
![2015-12-15_102456](https://cloud.githubusercontent.com/assets/8626952/11800343/9c2db288-a316-11e5-8154-56f3cfe49568.jpg)

Is there something I missed?

**Comment by dliw** [comment]
It looks like you didn't set up the resources correctly.

>And seems doesn’t compatible with fpCEF3-3.1750. 
The example as is does only work with the latest version.

**Comment by mercurylmy** [comment]
@dliw I don't think it is resources problem.
Here is the page in js32.exe(with the same cef 3.2454 dlls and other files):
<img width="472" alt="2016-01-03_203842" src="https://cloud.githubusercontent.com/assets/8626952/12078762/64915246-b25a-11e5-95e2-4f7cfe9dd653.png">

And I think cef 3.1750 is easier to redistribute. Only 2 files is necessary icudt.dll and libcef.dll.
Cef 3.2454 is much more files to redistribute.
So I hope it can compatible with fpCEF3-3.1750. 
Thank you very much.

**Comment by dliw** [comment]
Yes, the resources for the _LCLCefClient_ example have to be put in a separate folder. I thought this would be obvious.
I plan to further extend this example and maybe integrate some of the other examples, so I wanted the resources "out of the way".

It should be rather easy to get it working with CEF 3.1750 on Windows, but I would not recommend it. CEF still is improving and newer versions tend to have less problems.

CEF is heavy, but unfortunately there is no real alternative for Pascal, if one needs a fully featured browser component.

`OnBeforePopup` should be the place to catch new pages and open them in a new tab, but I still have to figure out, how to do it the best way.
Atm you can open new tabs only explicitly (e.g. via middle mouse click).

**Comment by mercurylmy** [comment]
@dliw 
Showing html pages with imbedding tabs are not my program’s main function. But also important. I design the program runs under Windows and Linux, so no ActiveX.
At the beginning I thought QT4 would fit my demand. But soon I find QTwebkit have some serious problem. It even damage all the program. And seems no one make a QT5 Binding.
Then I thought about replace it by CEF or Gecko. HtmlViewer is good, but can’t deal with complex JavaScript. Gecko is good too, but what I am doing is not a web browser. I can’t bear the runtime has so many confuse files. Then the only choose is CEF.  ╮(╯_╰)╭
I have learned C/C++. I can make games using SDL by either C/C++ or Pascal. But something like CEF is still too hard to understand.
What I want, is just a simplest imbedded tabbed browser component. Not so many big runtime files. I don’t need such latest feature, no video, no 3D or other things, CEF 3.1750 is enough for me.
And I tried to using middle mouse to click the link, not working.  : )

**Comment by dliw** [comment]
That sounds very familiar to me :smile: 
I'm still hope there will be a lightweight and cross-platform web component (HTML + JavaScript) for Pascal, but atm CEF is the best you can get.

For Win32 the difference between CEF 3.1750 and 3.2454 is about 18 MB, so in relation to the overall size it's not that much more.

On Linux 3.1750 is rather unstable and has problems, which got later fixed. Also multi tab is not possible with the older version on Linux.
If everything works, maybe it's fine to stick to the older CEF 3.1750 on Windows, but it's not a good idea when targeting Linux.


> And I tried to using middle mouse to click the link, not working.

For me it works as expected on Linux. Did you try on Linux or Windows?

**Comment by mercurylmy** [comment]
@dliw 
18 MB is too big. My most programs are 2~5MB (uncompressed).
I tried on Windows 8.1. And openSUSE. Both not works.
Is this seems odd? (¬_¬)
<img width="933" alt="2016-01-06_203149" src="https://cloud.githubusercontent.com/assets/8626952/12142972/5e921ec0-b4b7-11e5-9f11-86c7caf6413d.png">

**Comment by dliw** [comment]
What I wanted to say: CEF 3.1750 is _already_ > 50MB, so 18MB _more_ for CEF 3.2454 is not that much _more_. Overall it's certainly not little, that's true.

>I tried on Windows 8.1. And openSUSE. Both not works.

I use openSUSE 13.2 myself and middle click does open a new tab. Please try this __LCLCefClient__ Linux 64bit [binary](http://dliw.pfweb.eu/pool/client) for CEF 3.2454:
Release libraries and `icudtl.dat` in the same folder as the exe, resources in folder `Resources`.
Run with `LD_LIBRARY_PATH=. ./client`

From the screenshot it looks like you are using CEF 3.2454.1333 - you can find a newer version of the library in the fpCEF release section.

**Comment by mercurylmy** [comment]
CEF 3.2454.1333 is the latest version I can find in Branch 2454 on https://cefbuilds.com/. And I downloaded and tried your binary. Nothing different.
I don't know why the browser frames are come beyond the window. It's all fine using Firefox to open the same html file.
Here is the console output:
[konsole.txt](https://github.com/dliw/fpCEF3/files/80633/konsole.txt)

**Comment by dliw** [comment]
Starting with CEF 2.2454 for Linux you either need to compile CEF yourself or use the version I provided. The versions on cefbuilds works __only__ for CEF 3.1750 or older, see the readme.

Do you run Linux in a virtual machine (VirtualBox)? That's important information!
CEF seemingly has problems with the GPU. This is the reason for the wrong behaviour.
I can't really do anything about that, maybe someone on the CEF forums can help you solve the GPU problem.

**Comment by mercurylmy** [comment]
Yes, I run openSUSE in VirtualBox-5.0.10-104061-Win. I didn’t think that matter. VirtualBox emulates the hardware. But I haven’t seen any program broken because of this before. Well, if this problem only happens on a virtual machine. I think it ok. Because my target is real hardware. I just use VirtualBox for develop convenience.
The real problem is how to open the new page in tab whatever middle click or left click. (^-^)

**Comment by dliw** [comment]
Please try the unmodified LCLCefClient example on Windows. Open _example.com_ and middle click the link. A new tab should be opened.

If this does not work, there is something wrong with your setup.

**Comment by mercurylmy** [comment]
Yes, it works. But it's a URL started with `http://`. Not a local URL start with `file:///`.

**Comment by dliw** [comment]
Good, now we are getting somewhere :smile: 

I just tested on Linux with the following html file

    <html>
      <head><title>Test</title></head>
      <body>
        <a href="blah.html">test</a>
      </body>
    </html>

opened via `file://` protocol. Middle mouse click does open a new tab:
![tab](https://cloud.githubusercontent.com/assets/800832/12204900/90d628aa-b637-11e5-9e3d-3f30b991d67b.png)

**Comment by mercurylmy** [comment]
I see, the key is `OnBeforePopup`. Unfortunately I don’t know what is `OnBeforePopup`. I just want all new page open in tab, whatever by `<a href="xxx.html" target="_blank">xxx</a>`, JavaScript or other way. Hope you can fix this. (^-^)
Thank you very much.

**Comment by dliw** [comment]
Actually it wasn't that difficult, please see the changes I made.

Please close this issue if things now work for you.

**Comment by mercurylmy** [comment]
I see it. Brilliant!
Only a little problem is that address bar not change automatically. But I think it’s easy for me to fix.

> procedure ChromiumAddressChange(Sender: TObject; const Browser: ICefBrowser;
>       const Frame: ICefFrame; const url: ustring);
> 
> ……
> 
> procedure TWebPanel.ChromiumAddressChange(Sender: TObject; const Browser: ICefBrowser;
>   const Frame: ICefFrame; const url: ustring);
> begin
>   FMain.EUrl.Text := UTF8Encode(url);
> end;
> 
> ……
> 
> fChromium.OnAddressChange := @ChromiumAddressChange;

Now it’s perfect.
Thank you very much!

**Comment by dliw** [comment]
My bad, this also should be fixed now.
