### ISSUE TITLE
Can't get it to work on windows

### ISSUE THREAD

**Issue by aducom** [dliw/fpCEF3#19]
I followed the steps but I can't get the component to work. First it complains about missing properties like taborder. That line is made to comment for some reason so easy to fix. then it complains about missing backgroundcolor, adding a dummy fixes this issue. Than the debugger breaks on every cef_time_to_timet, and finally an empty browser screen appears, but it does not load any url. Not sure if it's a bug or not, but since this is my n-th attempt to get this working for various versions I still don't get it what I'm doing wrong or not. I loaded the 32 bits version and targetted the stuf to 32 bits.

I also redid the full installation and changed widgetset to w32 which solved the property issue. But I still can't get a webpage to show.

**Comment by zbyna** [comment]
I am not able to sort your issue out, but this component works in CodeTyphon 5.5 means Lazarus svn 31752 and fpc 3.1.1, win7 64 bit. I had simillar problems when upgrading my project which was **created by previous version of fpCEF**. This fixed my problem for me:
```
Tform.create()
...
Chromium.visible:=false;

Tform.show()
...
Chromium.visible:=true; 
```

But as I wrote above: my issue appearred only for projects not created in current version fpCEF.

**Comment by aducom** [comment]
I have it working now, but actually I don't know why it is currently. My only problem now is the needed subprocess, but that's a different issue. Tnx for your reply.
