### ISSUE TITLE
EOSError Exception

### ISSUE THREAD

**Issue by cyraid** [dliw/fpCEF3#20]
When starting the application, only when having Chromium control on Lazarus Form (GTK2).. (the only thing on the form) I'm running Ubuntu 15.10 (64bit), all other controls work.. Compiled libcef (a beast!) without tcmalloc, quick trace:

  $00000000004B6CCD line 449 of ../objpas/sysutils/sysutils.inc
  $00000000004B6BE1 line 438 of ../objpas/sysutils/sysutils.inc
  $0000000000750261
  $000000000060A177 line 7795 of include/wincontrol.inc
  $00000000006095EA line 7484 of include/wincontrol.inc
  $00000000004479B7 line 23 of include/scrollingwincontrol.inc
  $000000000044FFDD line 2589 of include/customform.inc
  $00000000004515C6 line 3055 of include/customform.inc
  $0000000000608A2E line 7349 of include/wincontrol.inc
  $000000000060A177 line 7795 of include/wincontrol.inc
  $000000000045B2B2 line 2178 of include/application.inc
  $000000000041E3DD line 16 of project.lpr

**Comment by cyraid** [comment]
My bad, such an awful newbie mistake. The library was actually in /usr/lib64 and not /usr/lib .. I have some new issues now though.. But now getting a different area.. It runs my 'subprocess', but SIGSEGV's at memcpy-sse2-unaligned.S (line 33), when it runs cef_browser_host_create_browser_sync, then CefBrowserHost::CreateBorwserSync, then CefBrowserHostImpl::Create, then CefBrowserHostImpl::CreateInternal, then CefBrowserHostImpl::CefBrowserHostImpl, then cef_string_utf16_set, then finally __memcpy_sse2_unaligned ..

**Comment by dliw** [comment]
If you don't need a debug build or a 32bit version of libcef, you could also use the binary I uploaded to the [release section](https://github.com/dliw/fpCEF3/releases).

I've never seen such an error myself, so I can only speculate. A full backtrace would be really helpful (see [here](https://github.com/dliw/fpCEF3#debugging)).

Does the `LCLSimple` example work for you (with your libcef or the libcef provided)?  Does anything change, if you put `libcef` into the folder with your executables and use `LD_LIBRARY_PATH=. `? Are all resources set up correctly?

**Comment by cyraid** [comment]
Turns out it was a bad build (2526).. I suppose there's a reason why cefbuilds.com even doesn't show the Linux 64bit one.. :p I tried yours, and it worked. Guess I'll have to use 2454 for now.. Thank you very much for your help!
