### ISSUE TITLE
cef3lib.pas(1002,44) Error: Incompatible type for arg no. 2: Got "TStringSplitOptions", expected "QWord"

### ISSUE THREAD

**Issue by mohsenti** [dliw/fpCEF3#21]
Hi!
I try compile library with fpc 3.1.1 but return below error !
cef3lib.pas(1002,44) Error: Incompatible type for arg no. 2: Got "TStringSplitOptions", expected "QWord"

**Comment by dliw** [comment]
Are you on Linux?
Try to change `None` to `X.None`.

I usually don't test with fpc trunk and with fpc 3.0 there is no error.

**Comment by mohsenti** [comment]
Yes, I using Ubuntu 14.04 LTS.
thank you, it's work.
