### ISSUE TITLE
Chromium component open new window and don't display any thing !

### ISSUE THREAD

**Issue by mohsenti** [dliw/fpCEF3#22]
Hi
I using fpCef3 in ubuntu and FPC 3.1.1.
when running application with chromium component,new window open and don't show anything and when close application raise below exception.

Project CefClient raised exception class 'External: SIGABRT'.

 In file '../nptl/sysdeps/unix/sysv/linux/raise.c' at line 56 

thank you.

**Comment by dliw** [comment]
More information is needed. Do you have a backtrace?

Are all resources set up correctly? Does `LCLSimple` work?

**Comment by dliw** [comment]
No additional information given.

**Comment by lucianomartini** [comment]
Hi, i know it is a closed, but i am having a very similar issue, but the component is working fine, it is just openning in another window and not in the form that i put it. 

It is not showing any errors like everything is ok, and is loading a google page, but it open in other window.

**Comment by lucianomartini** [comment]
In LCLSimple is in the same window, but it is showing a blank screen.
