### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by monobogdan** [dliw/fpCEF3#24]
Plugins not works, SIGSEGV.Here is my code:
var
cefplugins: TCefString;  
...
 Finalize(cefplugins);
  cefplugins.str := PChar16('/plugin/');
  cefplugins.length := sizeof(cefplugins.str);
  cef_add_web_plugin_directory(@cefplugins); 
cef_refresh_web_plugins;

**Comment by dliw** [comment]
What about `CefAddWebPluginDirectory('/plugin/');`? (cef3lib)

If you really want to use `cef_add_web_plugin_directory` directly, see how the string conversion works in `CefString()`.

**Comment by monobogdan** [comment]
Thanks :)28.12.2015, 16:33, "dliw" <notifications@github.com>:What about CefAddWebPluginDirectory('/plugin/');? (cef3lib)

If you really want to use cef_add_web_plugin_directory directly, see how the string conversion works in CefString().
