### ISSUE TITLE
How does Lazarus UI call a JavaScript function?

### ISSUE THREAD

**Issue by chanwit** [dliw/fpCEF3#28]
Hi,

I was trying to make a Lazarus UI calling a JavaScript function and get the return result.
I was following the C++ example here:

https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration

to register a JavaScript callback to the Lazarus-side and trying to call the callback later.
An exception was thrown without luck.

Do you have any example how to do this properly?

**Comment by dliw** [comment]
There is the [JavaScript example](https://github.com/dliw/fpCEF3/tree/master/Examples/JavaScript); the most important parts are in `handler.pas`. AFAIR it should be closely related to the link you provided.

Please keep in mind that CEF uses multiple processes (and threads), so you cannot access LCL/GUI from every place - that could be the reason for the exception.
An example how to properly do inter-process communication via CEF process messages can be found in the *DOMAccess* example (search for `*ProcessMessageReceived`).

**Comment by chanwit** [comment]
Thanks you for the fast reply @dliw !!

I set the browser to be a single process mode, but it couldn't help.
I'll give the DOMAccess a try and will update it here.

**Comment by dliw** [comment]
As mentioned in the *Hints* section of the readme: although CEF still provides a switch for the single process mode it basically is unmaintained and absolutely not recommended.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=3427#p6950

**Comment by dliw** [comment]
Closing this for now. Please reopen this issue or create a new one, if you need further help.
