### ISSUE TITLE
tcmalloc is now disabled in official builds

### ISSUE THREAD

**Issue by transcursion** [dliw/fpCEF3#30]
Hi dliw,

Thanks for you great project. Just giving you a heads up that tcmalloc is now disabled in official linux builds - [https://bitbucket.org/chromiumembedded/cef/wiki/AutomatedBuildSetup#markdown-header-linux-configuration](https://bitbucket.org/chromiumembedded/cef/wiki/AutomatedBuildSetup#markdown-header-linux-configuration). Official builds that disable tcmalloc are located at [http://opensource.spotify.com/cefbuilds/index.html](http://opensource.spotify.com/cefbuilds/index.html).

Since your readme.md mentions otherwise I'd figure I'd let you know about the recent change. Wasn't sure how else to reach you so hope you don't mind me opening an issue.

**Comment by dliw** [comment]
Thank you for the information.
Do you know if this also is true for cefbuilds.com ?

I won't change the readme right now as the official builds (http://www.magpcss.net/cef_downloads) do not provide the version 3.2526 which is needed for fpCEF at the moment.
Additionally I was told that the builds with tcmalloc enabled work, if LD_PRELOAD is used, but I could verify myself yet.

I will (re)test all possible options while doing the update to CEF 3.2623 and then update the readme accordingly.

**Comment by transcursion** [comment]
Marshall Greenblatt over at CEF only mentions spotify's builds.
[https://bitbucket.org/chromiumembedded/cef/issues/1827/tcmalloc-should-be-disabled-in-linux-osx](https://bitbucket.org/chromiumembedded/cef/issues/1827/tcmalloc-should-be-disabled-in-linux-osx)

**Comment by dliw** [comment]
Ok, thanks.

**Comment by dliw** [comment]
The latest release of fpCEF can be used with the spotify builds now. Readme has been updated accordingly.
