### ISSUE TITLE
fpCef3+Linux32+CEF binary with malloc disabled?

### ISSUE THREAD

**Issue by iso4free** [dliw/fpCEF3#31]
Hello!
I'm try to use fpCef3 in Linux Mint 17.3 (x32), but I cannot find compiled binaries with malloc disabled for version 3.2556.
I download sources for version 3.2556 and try to compile it using Code:Blocks IDE (compiling was success), but I don't know how to disable malloc. Can You help me to do it, please?
P.S. Sorry for my English

**Comment by dliw** [comment]
Hi,
you certainly mean CEF version **v3.2526** ?

Information on how to compile CEF are given in the [CEF wiki](https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding.md#markdown-header-building-from-source).

To disable tcmalloc all you need to do is to run
``
export GYP_DEFINES="use_allocator=none"
``
before executing  `automate-git.py`.


If you don't manage to compile it yourself, you could try to use the official binary (with tcmalloc) and use LD_PRELOAD:
```
LD_PRELOAD=$PATH_TO_LIBCEF/libcef.so
```
In this case you have to make sure, your application is always executed within an environment with this LD_PRELOAD set (think of debugging within Lazarus).
I had no time yet, to test how good this works, so using a CEF binary with tcmalloc disabled is still the recommended way.

**Comment by dliw** [comment]
With the latest release of fpCEF you can now use the official builds, as they don't have tcmalloc enabled.
