### ISSUE TITLE
Interception mouse events in Lazarus

### ISSUE THREAD

**Issue by AleksandrJS** [dliw/fpCEF3#32]
Hi,

The Object Inspector contains onKeyEvent.

Do you plan to make handling mouse events (onMouseEvent)?

I did not find examples of intercepting mouse events for TChromium
(Interested five buttons - 3 standard and 2 side).

Best Regards,
Aleksandr

**Comment by dliw** [comment]
CEF does not provide any callback / information about mouse state (AFAIK), so there is no (easy) way to achieve this.

Additionally CEF is more of an embedded "program" than a regular control, so it expects to have full control over keyboard, mouse and in fact even over the main window it is embedded in (!).
So even if mouse handling could be added by directly using the window system (like X on Linux), I think this would lead to interference with CEF.
So, no I don't plan to add mouse events - sorry.

Depending on what you need the mouse event for, you could use the fpCEF OSR (off-screen-rendering) component instead.

**Comment by zbyna** [comment]
As for mouse DOM events there was possibility to register so called event listener for particular event in CEF, but it was removed from CEF and fpCEF from  3.2454 see: https://bitbucket.org/chromiumembedded/cef/issues/933/provide-alternate-implementation-for
So there is possibility to realize that by java script engine in CEF but it does not seem like piece of cake activity 🙂

**Comment by AleksandrJS** [comment]
Thanks.

I will use Javascript
and Intercepting events from application or form.

**Comment by dliw** [comment]
@zbyna
Didn't think of that, but binding to javascript events indeed might be the best (but hard) way to go.

@AleksandrJS 
Please note that application and/or the form does **not** receive any events if the fpCEF component has focus.
You can close this issue if your question is answered.

**Comment by AleksandrJS** [comment]
@dliw 
Last question, please.
If the frame is on the form, the application can intercept events?

**Comment by dliw** [comment]
>Last question, please.
No problem, keep asking.

I don't really understand your question. Which "frame" on which "form" and what do mean by "intercepting events"?

Assuming you mean
- frame = fpCEF browser component = TChromium
- form = the form TChromium is parented to
- "intercepting events" = something like `TForm.FormMouseMove`

As long as TChromium does not have the focus, all events will work normally.

**Comment by AleksandrJS** [comment]
Thank you.
You understand correctly.
If I fail to capture TCromium events, then I will use Javascript.

Best Regards,
Aleksandr.
