### ISSUE TITLE
How to use the ResponseFilter

### ISSUE THREAD

**Issue by sqlnew** [dliw/fpCEF3#35]
Hi,
I want to realize response content filtering, see related functions and interfaces, such as cef_response_filter_filter, TCefResponseFilterOwn., but I do not know how to use, would you please tell me the use of methods, or to provide a corresponding demo, thank you very much.

**Comment by dliw** [comment]
Never used it myself, but this is how I think it should work:

1. Create a event handler for `TChromium.OnGetResourceResponseFilter`
2. Return an instance of `TCefResponseFilterOwn` in this handler

Documentation
 - [OnGetResourceResponseFilter](https://github.com/dliw/fpCEF3/blob/master/cef3api.pas#L3247-L3249)
 - [TCefResponseFilterOwn](https://github.com/dliw/fpCEF3/blob/master/cef3api.pas#L3494-L3524)

**Comment by sqlnew** [comment]
I follow your advice, have realized this function, and work well, thanks again.
