### ISSUE TITLE
WHY YOU GUYS DEMAND WaspAce TO DELETE WACEF ON BITBUCKET!!!

### ISSUE THREAD

**Issue by PonyPC** [dliw/fpCEF3#37]
waspace/wacef is most useful delphi cef3 framework, it helps me a lot at my work than other you. I don't see any about you guys' license of your free pascal project. You have no evidence to demand they delete the most useful cef3 project!

**Comment by quartexNOR** [comment]
You seriously have to be more spesific, who is "you guys" and what the hell is wacef?
And dude, use a spellchecked while your at it. If you are going to yell at people who dont even know what the fuck you are talking about, at least make it readable.

**Comment by dliw** [comment]
First of all - I never demanded, that the WACEF library should be closed. The only thing I did, was to point out, that the license of WACEF (MIT) wasn't compatible with the license of dcef3 or fpCEF (LGPL or MPL). This would be a major issue *if* WACEF had taken any code from those two. There were code snippets in WACEF which *looked like* they were copied 1:1 from fpCEF, but I obviously cannot prove it.
To say it very clearly: This is less an issue for me, than for those using WACEF and relying on correct licenses, especially in commercial applications.

If you have read the issue more closely, you would also have realized, that the author of WACEF actually didn't really want to maintain the library any more.
