### ISSUE TITLE
FPCEF3 printer dialog not showing on Debian 8 Linux

### ISSUE THREAD

**Issue by lucianomartini** [dliw/fpCEF3#39]
When i try to print the printer dialog did not appear. In Windows it is working fine. 

All Linux programs are able to print, so is not a issue with cups i think. 

No error messages, even if i run the app from a terminal.

**Comment by lucianomartini** [comment]
Because lazarus is not showing any errors, i tried to execute the app using[b] gnu debugger[/b] and when i click on the print option on cef menu, or in the print button (that i created), this error appear:
[quote][New Thread 0x7fff833fa700 (LWP 32077)]
[Thread 0x7fff833fa700 (LWP 32077) exited][/quote]

**Comment by dliw** [comment]
To be honest I never used or tested the CEF printing system on any system. To find your problem it would be really helpful for me to get some kind of example project or at least the relevant code snippets.

**Comment by lucianomartini** [comment]
Hi friend! For example, if i run a example app in Windows (in the folder examples of fpcef3), i am able to print using something like  Chromium.Browser.Host.Print; (try it yourself!) , or if i click with the right mouse button at the chromium component and select Print (if you dont want to change your examples)
With that the printer window appear and you can print fine! 

In Linux, executing the same method does not give any results, no errors or something... 
The print option are available by clicking with the right mouse button but does not open the printer window or something!

**Comment by dliw** [comment]
Well, now I remember. CEF itself does not implement printing support on Linux, instead the user has to implement it:
http://magpcss.org/ceforum/apidocs3/projects/(default)/CefPrintHandler.html

**Comment by lucianomartini** [comment]
Hellow i see something in the code like this: 

 // Implement this structure to handle printing on Linux. The functions of this
  // structure will be called on the browser process UI thread.
  TCefPrintHandler = record
    // Base structure.
    base: TCefBase;

    // Called when printing has started for the specified |browser|. This function
    // will be called before the other OnPrint*() functions and irrespective of
    // how printing was initiated (e.g. cef_browser_host_t::print(), JavaScript
    // window.print() or PDF extension print button).
    on_print_start: procedure(self: PCefPrintHandler; browser: PCefBrowser); cconv;

    // Synchronize |settings| with client state. If |get_defaults| is true (1)
    // then populate |settings| with the default print settings. Do not keep a
    // reference to |settings| outside of this callback.
    on_print_settings: procedure(self: PCefPrintHandler; settings: PCefPrintSettings; get_defaults: Integer); cconv;

    // Show the print dialog. Execute |callback| once the dialog is dismissed.
    // Return true (1) if the dialog will be displayed or false (0) to cancel the
    // printing immediately.
    on_print_dialog: function(self: PCefPrintHandler; has_selection: Integer;
      callback: PCefPrintDialogCallback): Integer; cconv;

    // Send the print job to the printer. Execute |callback| once the job is
    // completed. Return true (1) if the job will proceed or false (0) to cancel
    // the job immediately.
    on_print_job: function(self: PCefPrintHandler; const document_name, pdf_file_path: PCefString;
      callback: PCefPrintJobCallback): Integer; cconv;

    // Reset client state related to printing.
    on_print_reset: procedure(self: PCefPrintHandler); cconv;

    // Return the PDF paper size in device units. Used in combination with
    // cef_browser_host_t::print_to_pdf().
    get_pdf_paper_size: function(self: PCefPrintHandler; device_units_per_inch: Integer): csize_t; cconv;
  end;    


This is not a issue so i think this can be closed, but is there a way that i can chat to you for help about this implementation?

**Comment by lucianomartini** [comment]
Closing because is not a fpcef issue.

**Comment by dliw** [comment]
>This is not a issue so i think this can be closed, but is there a way that i can chat to you for help about this implementation?

You can ask questions via this issue tracker (there is a label `question` for this purpose). Or you can write me an email if you prefer: dev.dliw@gmail.com
