### ISSUE TITLE
Disable the embeded pdf reader, but download the pdf or open in another program

### ISSUE THREAD

**Issue by lucianomartini** [dliw/fpCEF3#42]
I see that chromium included some kind of pdf reader, i dont want to use it.

There is some way to force chromium to execute a external program for this pdf or to start download?

Thank you so much.

**Comment by dliw** [comment]
This is a general question about CEF and in no way specific to fpCEF.

A quick search gave me the answer:
 - http://magpcss.org/ceforum/viewtopic.php?f=17&t=13984
 - https://bitbucket.org/chromiumembedded/cef/issues/1565/re-implement-pdf-viewer-using-out-of

**Comment by lucianomartini** [comment]
I see the topics, and they are saying that the parameter is not working, and there is a lot of unsolved topic about this in the forum. They even suggested to edit the C++ code parts. 

But i discovered a way, lets share this with you. 
You need to set:
CefCommandLineArgsDisabled:=false;    

On FormCreate, and now the command line argument will work when passed to the main app, i dont know a better way for doing this. But it is the better way than i found.

**Comment by dliw** [comment]
Are you speaking about `--disable-pdf-extension`? It works for me:

![fpcef no-pdf](https://cloud.githubusercontent.com/assets/800832/21722689/fe239266-d42d-11e6-916d-fc1b0f6175db.png)

**Comment by lucianomartini** [comment]
For some reason for me not until i set CefCommandLineArgsDisabled:=false; but i will test it more.
