### ISSUE TITLE
Question: Wait download completes

### ISSUE THREAD

**Issue by lucianomartini** [dliw/fpCEF3#43]
Thank you ! Now the download works like a charm. I want to know if there is a way of wait the download completes before i run the next command:

```
    files.Add('/tmp/lastfile.pdf');      

    FreeAndNil(files);

    RunCommand('/usr/bin/evince',['/tmp/lastfile.pdf'], s);   
```

It is running the command at the same time the file is being saved or something like this.

**Comment by dliw** [comment]
You can use the `OnDownloadUpdated` callback to get status updates of all downloads. The `downloadItem` parameter of this callback allows you to get further information about the download item.

E.g. you can check, if the download is completed via `IsComplete`.


Again: all of this is **not** specific to fpCEF, so it is better to ask on the CEF forums. I like to help as much as I can, but I cannot guide you through the process of creating a complete web browser. CEF is **not easy-to-use** and one needs pretty good programming skills and knowledge (multithreading, behavior of interfaces, some knowledge about the inner workings of CEF, ...) to work with it.

If you are doing a private project, please try a bit harder to find answers for your questions, mostly it is really only a matter of using Google. If it is a commercial project, try to find someone else to implement the things you need or post a bounty.

**Comment by lucianomartini** [comment]
But if i ask in the CEF forum they will ask me why i am using lazarus? Why not to use C++... or something like this? 

Thank you and sorry.!

**Comment by dliw** [comment]
>But if i ask in the CEF forum they will ask me why i am using lazarus? Why not to use C++... or something like this?

Well, no. Others are using Java or C# wrappers, so that's no problem.
The interface is the same and the class abstraction is not too much different. For questions about the CEF API the language used really does not matter.

You cannot expect Pascal example code, of course - but programming is the job of the programmer 😄
