### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by dtamade** [dliw/fpCEF3#44]
Where do I download the version of the binary file?

**Comment by dliw** [comment]
Do you mean the CEF binary? The download locations are in the readme, the official one is http://www.magpcss.net/cef_downloads.

For the latest foCEF version you need CEF 3.2743; you can use the version filter on the top of the page.

**Comment by lucianomartini** [comment]
You need to click on the **show more builds** link to see the other versions:

For Windows 32 bits for example the cef 2743: 
http://opensource.spotify.com/cefbuilds/cef_binary_3.2743.1449.g90ba67d_windows32.tar.bz2

**Comment by dtamade** [comment]
thanks

**Comment by dtamade** [comment]
FPCEF now does not support WINXP?

**Comment by dliw** [comment]
CEF does not support WinXP any more, as Chromium does not support it any more.

See https://github.com/cefsharp/CefSharp/wiki/Windows-XP-No-Longer-Supported

You can use an older release of fpCEF with a version of CEF though.
