### ISSUE TITLE
Unknown property: "TabOrder"

### ISSUE THREAD

**Issue by websea** [dliw/fpCEF3#45]
Hi.

I've tried to compile this package with Lazarus 1.6.2 and fpc 3.0
The following error occurs: Unknown property: "TabOrder".
![capture](https://cloud.githubusercontent.com/assets/5376332/22454446/90bd4b8a-e78e-11e6-92b6-cef84c71f9d1.JPG)
Please help.
Thank you.

**Comment by dliw** [comment]
Are you updating from an older fpCEF version?

Open the `.lfm` file(s) of the form(s) that include a browser component and remove the line `TabOrder = X`. This should fix your issue.

**Comment by dliw** [comment]
It seems this issue is solved. Please reopen if this is not the case.

**Comment by dliw** [comment]
`TChromium` appears in tablist, so `TabOrder` must be published. Fixing this ASAP.
