### ISSUE TITLE
Assembler window: libcef!GetHandleVerifier

### ISSUE THREAD

**Issue by tandriamirado** [dliw/fpCEF3#46]
Good day,
fpCEF3 worked fine a few months ago (Linux + Windows 8.1), Lazarus 1.6
What have changed is Lazarus: v1.6.2

When running any app using fpCEF3, including the examples, I always get the assembler window with 'libcef!GetHandleVerifier'. So I downloaded the last version of fpCEF3, and cef_binary_3.2743.1449.g90ba67d_windows32 : same issue!
(screenshot attached)

Do you know how to solve this one? Thaks in advance
![20170131-fpcef_bug_assembler_window](https://cloud.githubusercontent.com/assets/395776/22474045/d9fecd3e-e7eb-11e6-86e3-189a45237bc4.png)

**Comment by tandriamirado** [comment]
Some additional informations, as I'm trying to tackle this one. And I'm sure I'm not alone facing this issue:
* When 'visible := false', there's no crash (but the Chromium component is invisible, of course)
* when I put a TButton to set 'visible := true', clicking on this button causes the crash again.
* Calling 'CefInitDefault;' will cuse the problem. The assembler window is then opened by:
- line 1630 in cef3own:
`If Assigned(PCefBase(FData)^.add_ref) then PCefBase(FData)^.add_ref(FData);`
- which is called (AFAIK) by line 473 in cef3lib:
`ErrCode := cef_initialize(@Args, @settings, CefGetData(app), nil);`

It seems to be a configuration problem and/or painting of the component.. but I'm no sure..

I hope this helps..

**Comment by dliw** [comment]
Hello.
Do you see this problem with one one of example projects (LCLSimple), too? Does this also happen on Linux, or is this Windows only?

I tried to reproduce (Win7, 64bit, 32bit Lazarus 1.6.2, latest fpCEF (master, not the tagged release), the CEF binary you mentioned), but it works for me. Also I cannot remember seeing this error before.

So unless one of the example projects behaves the same, or you provide more info, how your setup looks like (relevant code), I cannot help, I'm afraid.

Some general points to check:
- Are the resources set up correctly? Does Lazarus start the program in the correct working directory?
- If a subprocess is used (recommended): resources, working directory?
- Do you use the release binaries (dlls) of CEF? Debug usually has issues and cannot be used.
- Are there any relevant warnings / errors in the `debug.log` file?

**Comment by tandriamirado** [comment]
Hello,

* I can't test on Linux yet, as my Internet connection is very slow those days so I could download CEF3 for windows but not the linux one.
* Same issue with 3 examples: WinMinimal, LCLSimple, LCLCefClient
* The files and directory structures were ok and worked fine a few months ago, AFAIR what have changed was Lazarus version 1.6.2. That's why I updated fpCEF3 and CEF3 but same issue.. setting CefResourcesDirPath and CefLocalesDirPath don't help and when debugging their values are correct
* I'm using the tagged release, https://github.com/dliw/fpCEF3/releases/tag/v3.2743 , as I thought it is more stable than master
* no subprocess used, to keep testing as simple as possible, but I'll try to use the included SubProcess example
* I use the 'release' binaries, as 'debug' is a bigger tar.gz to download :P
* all debug.log have this line in common:
[0131/185400:ERROR:icu_util.cc(179)] Invalid file descriptor to ICU data received.

Thank you for your time ;)

**Comment by dliw** [comment]
>Invalid file descriptor to ICU data received

Please check if the file `icudtl.dat` is in the same folder / place as `libcef.dll`.

**Comment by tandriamirado** [comment]
It works! By copying icudlt.dat from the Resources folder to the project's folder! So:

Is the best practice to copy BOTH Release and Resources directories in the project's exe folder, now? (so we don't need CefResourcesDirPath anymore?)

OR is there something like 'CefIcuDataDirPath' to be set to CefResourcesDirPath in order to make CEF find this file? I couldn't find such a procedure..

Thanks for your time!

**Comment by dliw** [comment]
Well, it is clearly stated in the readme:

> However in any case icudtl.dat **must** be in the same folder as the CEF library!
