### ISSUE TITLE
SIGSEGV on Linux

### ISSUE THREAD

**Issue by dibok** [dliw/fpCEF3#47]
Hi,

I followed all instructions (cthread, files path etc), LD_LIBRARY_PATH point to my project dir, LibHandle<>0 but still at line:

`ErrCode := cef_initialize(@Args, @settings, CefGetData(app), nil);`

...getting:

> Project project1 raised exception class 'External: SIGSEGV'.
> 
>  In file '../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S' at line 245

My init code is:
```
procedure TForm1.FormCreate(Sender: TObject);
var
  PrjPath: ustring;
  Lang, FallbackLang: string;
begin
  PrjPath := UTF8Decode(GetCurrentDir + PathDelim);
  CefLocalesDirPath := PrjPath + 'locales';
  GetLanguageIDs(Lang, FallbackLang);
  CefLocale := UTF8Decode(FallbackLang);
end;  
```

**Linux Mint 18.1 64bit**, KDE edition
**Kernel 4.8.0-36** generic
**Lazarus 1.6.2**
**FPC 2.6.4**
**02/16/2017 - CEF 3.2924.1570.g558741c / Chromium 56.0.2924.76** "standard" edition but also tested with "minimal" - same error

Anyone can confirm this bug?

**Note:** Simple C client demo is working fine

Regards

**Comment by dibok** [comment]
SOLVED!

Looked at git tags and last stable version of fpCEF3 was 3.2743 so downloaded this version instead of master and also downloaded CEF3 binaries for version 3.2743 and everything is working perfect!

But still getting weird console stdout logs:

> [0221/000541:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
> QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No file or directory
> QFileSystemWatcher: failed to add paths: /home/dibo/.config/ibus/bus
> Bus::open: Can not get ibus-daemon's address. 
> IBusInputContext::createInputContext: no connection to ibus-daemon 
> [0221/000940:WARNING:ipc_message_attachment_set.cc(57)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
> [0221/000943:WARNING:quota_manager.cc(1845)] Create directory failed for path
> [0221/000943:WARNING:quota_manager.cc(1845)] Create directory failed for path
> [0221/000943:WARNING:quota_manager.cc(1845)] Create directory failed for path
> [0221/000947:WARNING:quota_manager.cc(1845)] Create directory failed for path

Are they important? How to disable these logs?

**Comment by dibok** [comment]
Also sometimes GUI app is not terminating permanently (main window is closing but process still exists). Once even had exception when closing app

**Comment by dliw** [comment]
For the first part: CEF versions are not compatible and API (still) changes, so you have to use the correct CEF version.
If you for some reason need a newer version: I'm currently working on the update to 3.2840, I hope to get it done sometime next month.

>Are they important?

Speaking for the part you cited, there is nothing unusual.


>How to disable these logs?

See [here](https://bitbucket.org/chromiumembedded/cef/issues/903/debuglog-is-always-created)...


>Also sometimes GUI app is not terminating permanently (main window is closing but process still exists). Once even had exception when closing app

Can you reproduce this behavior in either the `LCLSimple` or the `LCLCefClient` example?
One reason this happens could be stale interface references, that prevent CEF from shutting down.

But again (as in your other issue) there is a problem with CEF and LCL: CEF expects to have full control over the window it is embedded into, but so does the LCL. CEF provides API to better control the shutdown process, but I did not find a way yet on how to do things properly and make CEF and the LCL happy. At the moment CEF is "forcefully" killed, whenever the TChromium component is destroyed.
