### ISSUE TITLE
Can't use on TPageControl with Qt widgetset

### ISSUE THREAD

**Issue by dibok** [dliw/fpCEF3#48]
Hi,

As in title. I can drop TChromium on pages and it work fine at design time but when run program then all TChromium instances have main window as parent

Lazarus 1.6.2, Qt widgetset
FPC 2.6.4
Linux Mint 18.1, KDE Edition, Plasma 5
Chromium 3.2743 "minimal" edition
fpCEF3 master (but same bug on tag 3.2743)

Regards

**Comment by dliw** [comment]
You can use a TPageControl, but not this way (on Linux). Please see the LCLCefClient example on how to create a tabbed browser.

Background info (not the first time I wrote this, I really should put this somewhere into the wiki...):
On Linux fpCEF currently embeds CEF into the X window of the form the TChromium component is paced on, which causes the effect you see. I tried embedding into the first X window found on the hierarchy, but this didn't work reliably.
I did not found a perfect solution to this problem, embedding and making the component behave like any other LCL control is not a trivial task.

**Comment by dibok** [comment]
Indeed, on LCLCefClient it is working fine but I don't understand where is difference. It is also adding TChromium as a parent of TTabSheet:

```
    fChromium := TChromium.Create(Self);
    fChromium.Parent := Self;
    fChromium.AnchorAsAlign(alClient, 0); 
```

**Comment by dliw** [comment]
The main difference is `DoShow` and `DoHide`, CEF has no idea of what a component is, it embeds into a X **window**.

Furthermore the late creation of TChromium makes sure, all other components are already created.

**Comment by dliw** [comment]
Closing this for now. Please reopen this issue or create a new one, if you need further help.
