### ISSUE TITLE
CefV8Value::CreateFunction() equivalent in FPC

### ISSUE THREAD

**Issue by z505** [dliw/fpCEF3#51]
In the CEF C++ documentation there is a way to create a function:

CefV8Value::CreateFunction("myfunc", handler);

(a native function that then can be called by Javascript code, AFAIK)

Is there anything equivalent for freepascal/lazarus ?
I was thinking RTTI was the way, but not sure, there are probably multiple ways, as CEF is quite complex of an API.

From the documentation:
"CEF supports the creation of JS functions with native implementations. Functions are created using the CefV8Value::CreateFunction()"

https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration.md#markdown-header-js-functions

Also, do you accept Donations (money) for your great contributions to this project :-) and thanks for making it work with fpc

**Comment by z505** [comment]
The Javascript example is good. (all your examples are nice short simple and easy to read)

I'm having trouble understanding why a ShowMessage call works inside the TMyHandler.Execute function which is GUI code, but these GUI calls will not work

function TMyHandler.Execute(const name : ustring; const obj : ICefv8Value;
  const arguments : ICefv8ValueArray; var retval : ICefv8Value;
  var exception : ustring) : Boolean;
begin
  // return a value
  retval := TCefv8ValueRef.NewString('TMyHandler');
  // This does not work:
  MainForm.Log.Lines.Add('In execute function');
  // This works
   ShowMessage('abc def');
  Result := True;
end;       

At the top of your source file it says "so there is no access to GUI "
But a showmessage is gui related code, no?

Sorry, I'm confused, and obviously a newbie to CEF

**Comment by dliw** [comment]
> But a showmessage is gui related code, no?
It depends on the perspective, `ShowMessage` is the exception to the rule:
`ShowMessage` can be called from any thread and it does *not* depend on any controls on your form, so it is perfectly ok to call it.

No access to GUI means, you cannot access the controls on your form, as the handler gets executed on a different thread.

**Comment by z505** [comment]
And how about global variables outside a function, any warnings with using these? As global variables (even unit local ones in the implementation section) cause thread issues.
I didn't know handler used threads, I thought the architecture was based on interprocess communication, but that's because I have not fully read the sources.  Combining IPC and threads, now makes it confusing ;-) but CEF is a powerful useful tool regardless.

**Comment by dliw** [comment]
Ouch, of course the handler is executed on a different **process**. Sorry for the confusion.

**Comment by z505** [comment]
Well some programming languages are now treating processes and threads as the same thing, in an abstract kind of way.  (concurrent programming where the low level details of whether it is a thread or a process becomes an implementation detail only, the programmer should not care...)

I'm having trouble understanding how a procedure, inside a Pascal program, can run inside another process. I understand the concept when it is a DLL, and a DLL calls a procedure in an EXE, but an actual "process" calling another procedure? Hmmm...
The IPC knowledge I have is you send strings over sockets or using messages and such... 
I do not for the life of me understand how a procedure, in a pascal program, can be called (executed) inside C++?

**Comment by dliw** [comment]
>I'm having trouble understanding how a procedure [...]

The answer is rather simple:
All the other processes are subprocesses (or your main executable when no subprocess is given). After initialization CEF is called and only return when the process is stopped ([see here](https://github.com/dliw/fpCEF3/blob/master/Examples/SubProcess/subprocess.lpr#L20)). Therefore your handlers need to be defined inside the subprocess.

When no subprocess is given, the main program is used instead (*Task Manager* can prove this 😃). After all the handlers are created, there is a call to CEF which does not return, if the process is not the main process. At that point CEF has full control over the process and can call all registered handlers / functions / callbacks ...

**Comment by dliw** [comment]
Closing this now. Please reopen this issue or create a new one, if this is still unsolved.
