### ISSUE TITLE
Cannot get it to work in lazarus

### ISSUE THREAD

**Issue by aducom** [dliw/fpCEF3#52]
I installed the components and got a property does not exist error on TabOrder. Searching in the source that could easily be fixed as this line was commented out (why?). 

published
      property Color;
      property Constraints;
      //property TabStop;
      property Align;
      property Anchors;
      //property TabOrder;
      property Visible;

I looked into the cef3 libaries and resources, but when downloaded and set to the project directory I get an error that the cef3library has the wrong version. 

The advised version on the Lazarus wiki differs from the one mentioned here on git, but both fail.

**Comment by dliw** [comment]
Are you trying to open an existing project? See issue #45 on how to proceed.
I *think* I commented this out, because it has no effect, but I'm not sure - I will check this.

For the latest release you need CEF version 3.2840. Please try to reproduce with the LCLSimple example, I tested on all platforms, so things really should work.

**Comment by aducom** [comment]
I tried the solution of #45. It did not work, most likely because the components are derived from an object that contains this property. It's a visual property, so it's in the tablist. 

I upgraded to the latest Lazarus, removed the cef3 package fully, replaced it with the latest version and rebuild Lazarus IDE. I downloaded the 3.2840, but there are a lot of these:
11/11/2016 - CEF 3.2840.1517.gd7afec5 / Chromium 54.0.2840.99
11/05/2016 - CEF 3.2840.1515.g1b7ab74 / Chromium 54.0.2840.90
... 6 others
10/17/2016 - CEF 3.2840.1494.g7fe3d03 / Chromium 54.0.2840.59

I tried the first and the last. 

I have a working (old) version so I think that I haven't done anything wrong, but will try tomorrow again. I see that the wikipage has changed a bit and references straight to https://github.com/dliw/fpCEF3/releases/tag/v3.2840 now. Will retry tomorrow. 

tnx, Albert

**Comment by dliw** [comment]
>I downloaded the 3.2840, but there are a lot of these:
Well, yes. It's always the newest one you need.
For the [branch 2840](https://bitbucket.org/chromiumembedded/cef/branches/) the newest [commit](https://bitbucket.org/chromiumembedded/cef/branch/2840) is ffd843c.
If I input "3.2840" into the version filter field on http://opensource.spotify.com/cefbuilds/index.html, only the version `11/19/2016 - CEF 3.2840.1518.gffd843c / Chromium 54.0.2840.99` is shown, which is the right one.

**Comment by aducom** [comment]
Ok, well I tried it on another dev system. I didn't change taborder so I would leave it for now. This is what I did:

Installed Lazarus
Installed the components
Copied the correct version resource and release into the simpledemo
Recompiled the ide to enable the components
Opened the subprocess, changed linux to win32 (running lazarus 32)
Compiled and moved the exe into the simpledemo
Opened simpledemo and change linux to win32
Compiled and run
The application opens with a blank form
Entered an url and click on the button
Nothing happens...

But it's a different outcome than on my other system. Thus I will try it again there tomorrow.

**Comment by dliw** [comment]
Just to be sure:
If you don't set `CefResourcesDirPath` or `CefLocalesDirPath` the directory must look like this:
```
├── cef_100_percent.pak
├── cef_200_percent.pak
├── cef_extensions.pak
├── cef.pak
├── d3dcompiler_43.dll
├── d3dcompiler_47.dll
├── devtools_resources.pak
├── icudtl.dat
├── libcef.dll
├── libEGL.dll
├── libGLESv2.dll
├── locales
│   └── ...
├── natives_blob.bin
├── snapshot_blob.bin
├── subprocess.exe
└── widevinecdmadapter.dll
```

However, even if you **do** set `CefResourcesDirPath`, `icudtl.dat` **must** be in the same folder as the CEF library.

**Comment by aducom** [comment]
Mmm, that's an issue on my side, subprocess.exe has been compiled to subprocess32.exe. Changed it and it works! tnx for your support.
