### ISSUE TITLE
How to get more items in Arguments in Execute function 

### ISSUE THREAD

**Issue by z505** [dliw/fpCEF3#54]
Hi, in the function (js example):

```
function TMyHandler.Execute(const name : ustring; const obj : ICefv8Value;
  const arguments : ICefv8ValueArray; var retval : ICefv8Value;
  var exception : ustring) : Boolean;
```
there is a paramater called Arguments, and you can retrieve arguments[0] by setting:

`cef.test.test_param = "something"`

The string "something" can be retrieved by checking arguments[0]

What woul the arguments[1], arguments[2], etc. be for?

If cef.test.test_param can really only set one argument, how would you set multiple arguments? I'm wondering if that is for something else maybe.

thanx!

**Comment by dliw** [comment]
I think, I need to make some things clear:

- `test_param` is not a variable, but rather something like a _property_ in Pascal (don't know the correct JavaScript term). Getters and setters are defined [here](https://github.com/dliw/fpCEF3/blob/1d107dae138aadad1add29d3b6d04509635cd641/Examples/JavaScript/handler.pas#L76-L83).
- Whenever `test_param` is accessed,  the _native functions_ `GetTestParam` and `SetTestParam` are called, which means `TMyHandler.Execute` gets called with either zero or one argument.

Also see the comment for  [TCefV8Handler.Execute](https://github.com/dliw/fpCEF3/blob/1d107dae138aadad1add29d3b6d04509635cd641/cef3api.pas#L4133-L4137).

**Comment by z505** [comment]
Correct, it is very much like a object pascal property, as it has "side effects" and executes code as part of its assignment, whereas a variable just sets a value. I also, like you, don't know what javascript calls this and am too lazy to look it up at the moment.

But is there ever arguments[2], arguments[3], arguments[4], etc.  .... arguments[30]

This was what I am wondering. i.e. if it has the ability to make as many arguments as you wish, when would you ever use arguments[2], arguments[6]?

And sorry for opening an "issue" this is more of a documentation/example/question than it is an issue. Might even start documenting this project myself at some point, and upload some html docs/pdf docs :-)

**Comment by dliw** [comment]
Yes, there can be an arbitrary number of arguments:
Something like
```
native function SetTestParam();
SetTestParam(arg1, arg2, ..., argn);
```
will call `Execute` with *argn* arguments.

**Comment by dliw** [comment]
Closing. Please reopen if the question still persists.
