### ISSUE TITLE
Doesn't compile on FPC trunk

### ISSUE THREAD

**Issue by dimsa** [dliw/fpCEF3#55]
Lazarus 1.7 from https://www.getlazarus.org/
FPC 3.1.1.
SVN Revision 51308
Windows 10 (1511, Build 10586.916 )

Trying to compile cef3.lpk and got error in method

```
procedure TCefBrowserHostRef.ImeSetComposition(const text: ustring; underlinesCount: TSize;
  underlines: TCefCompositionUnderlineArray; const replacementRange, selectionRange: TCefRange);
Var
  t: TCefString;
begin
  t := CefString(text);
  PCefBrowserHost(fData)^.ime_set_composition(fData, @t, underlinesCount, @underlines,
    @replacementRange, @selectionRange);
end;        
```

cef3ref.pas(1579,1) Error: Local variables size exceeds supported limit

**Comment by dliw** [comment]
I only support the latest stable version of Free Pascal, which currently is 3.0.2. I didn't test lately, but I'm rather sure version 2.6.4 also works.

You have to report a bug against Free Pascal trunk, this is not a fpCEF bug.

**Comment by dimsa** [comment]
Thank you! I changed compiler. Now all works fine (3.0.2). Problem was in x86 compiler. Trunk that I used hasn't 64bit compiler. My mistake. Thank you for your work!
