### ISSUE TITLE
Installation problem,

### ISSUE THREAD

**Issue by Cosmotan** [dliw/fpCEF3#56]
According to this : https://github.com/dliw/fpCEF3/blob/master/Readme.md

Download CEF3 from here "http://www.magpcss.net/cef_downloads" and copy all files from either Debug or Release to the folder your .exe is / will be in. 
Right, if i download the Win64 Release or Debug file : http://opensource.spotify.com/cefbuilds/cef_binary_3.3071.1649.g98725e6_windows64_release_symbols.tar.bz2 or "http://opensource.spotify.com/cefbuilds/cef_binary_3.3071.1649.g98725e6_windows64_debug_symbols.tar.bz2" or 
The archive has only one file called libcef.dll.pdb
its some kind of M$ program database file and i cannot extract it.

Really, can someone make a serious how to to get this working on Lazarus or is this project dead?

I will like to embed the browser in my app but this is not working like it should be.

Cheers.

**Comment by dliw** [comment]
Hello,
no, this project is not dead. I just don't have the time to update right now, but I hope to catch up with CEF by the end of August.

1. From the readme
> See changelog or release tag for the currently supported version, other versions (older or newer) may work, but are not recommended.

So: for the latest version of fpCEF you need **CEF 3.2924**.

2. You are downloading the debug symbols, why not _Standard Distribution_ or _Minimal Distribution_?
Try this link: http://opensource.spotify.com/cefbuilds/cef_binary_3.2924.1575.g97389a9_windows64_minimal.tar.bz2

**Comment by Cosmotan** [comment]
Well, i have tried to use the debug or release version becuase the readme tells me so "https://github.com/dliw/fpCEF3/blob/master/Readme.md" and i don't have any luck with standard or minimal.
As you suggested i download the Minimal Distribution from the link you provided, then i have extract the 2 directory's "Release" and "Resources" into the LCLSimple directory and compile it, the application start i can enter a url but the page don't get loaded, no its not some kind of firewall/Antivirus problem. 
I have observed that the TMainform.ChromiumTitleChange event get fired up but the Title variable (ustring) is empty, so the Form caption is "Browser -" and the Browser variable (ICefBrowser) looks empty to, in the debugger  :
Browser = <ICEFBROWSER> = {
  <ICEFBASE> = {
    <IUNKNOWN> = {}, 
    }, 
  }

OS : M$ Win 10
Lazarus version :  Lazarus 1.8.0RC3 r55409 FPC 3.0.2 x86_64-win64-win32/win64
Chromium : Version 59.0.3071.115 (Official Build) (64-bit)
CEF : cef_binary_3.2924.1575.g97389a9_windows64_minimal.tar.bz2

The cef file list has this :
03/01/2017 - CEF 3.2924.1575.g97389a9 / Chromium 56.0.2924.76

do i need to have the same Chromium version (56.0.2924.76) to use the 3.2924.1575.g97389a9 cef .dll's ?

What can i do to get this working?

Cheers

**Comment by dliw** [comment]
The files are ok, but your setup still is wrong. Please see http://wiki.freepascal.org/fpCEF3, maybe this makes things clearer.
Also LCLSimple needs a subprocess exe (compile from examples and put it into the LCLSimple directory).

But I see, I need to rework the Readme to make things more clear.

**Comment by dliw** [comment]
> so i have need to adjust the line to

Sorry, I should have mentioned that. You are supposed to rename the generated _subprocess32.exe_ or _subprocess64.exe_ to _subprocess.exe_.
This is not ideal, but saves me a lot of time when debugging.

>Maybe you can give me a one more small advice
You may take a look at the **DOMAccess** example. It fetches the DOM on keypress.
AFAIK CEF has no built-in functionality for saving the whole page including images etc., so you have to parse the DOM and fetch the files yourself.

But be warned: CEF is not easy to master and it may be easier to download the webpage via synapse, fcl-net or similar libraries.

**Comment by Cosmotan** [comment]
I only need the HTML-Source to be saved to a file or copy to clipboard...
i know synapse or indy well, the problem is if the page has some javascript stuff which generates parts of the html-page dynamically synapse will not get this and you miss a lot, if however you save the page from chromium as "Webpage HTML-Only" then you have the whole page saved. Thats why synapse or indy is not a option. 

Is there a good documentation for CEF3 where i can look deeper into it ?

The other solution will be to start the chromium-browser and then from my app sendkeys to the chromium window (CTRL-T open a Tab)  send the url <ENTER> then <CTR-S open save dialog> ...

but here you don't know has chromium already loaded the page completely, you can wait lets say 5 sec and then continue, the TChromium component however gives you a lot of events like OnLoadEnd and then you know you can continue to save and analyze the page.

Any help will be nice on this

Thx

Cheers

**Comment by dliw** [comment]
>Thats why synapse or indy is not a option.

True. I was just saying...

>Is there a good documentation for CEF3 where i can look deeper into it?

The official docs are [here](http://magpcss.org/ceforum/apidocs3), but it seems they are no longer up to date.

Also the whole documentation can be found inside the comments in [cef3api.pas](https://github.com/dliw/fpCEF3/blob/master/cef3api.pas).
This is the "raw" CEF C API translation. You don't need to use these directly, rather you use the OOP abstraction, which is the classes in **cef3ref.pas** and **cef3own.pas**.

>Any help will be nice on this

There is a method [get_source](https://github.com/dliw/fpCEF3/blob/v3.2924/cef3api.pas#L1840), which may already be all you need. The corresponding method in the abstraction is [here](https://github.com/dliw/fpCEF3/blob/v3.2924/cef3ref.pas#L377).
You can get the main frame via ```Browser.MainFrame``` or [these methods](https://github.com/dliw/fpCEF3/blob/v3.2924/cef3ref.pas#L60-L66).

If this for some reason is not good enough, you can access the DOM like I mentioned before and extract the source manually.

I hope this is enough to get you started.

**Comment by dliw** [comment]
I've reworked the readme, so it should be much clearer now.
Closing this issue now. Please reopen  or create a new one, if this is still unsolved.
