### ISSUE TITLE
Help me ! 

### ISSUE THREAD

**Issue by xiximitho** [dliw/fpCEF3#57]
I'm having problems with fpcef, I can not compile anything, because it gives = " project raised error exception class 'External: SIGILL'.
 In file '../../content/app/content_main_runner.cc' at line 680. "
 
i'm using linux mint 17.3 64bits with QT, i also tried with GTk2 but the problem still appears.  Lazarus 1.6.4 and using the cef binary version 3.2924 and fpCEF(branch) v2924.

**Comment by dliw** [comment]
https://chromium.googlesource.com/chromium/src.git/+/56.0.2924.76/content/app/content_main_runner.cc#680

I'm rather sure your setup is missing the file **icudtl.dat**.
From the readme:

> Apart from the files in the Debug or Release folder, CEF needs the files / folders from the Resources folder. Unless you set CefResourcesDirPath and CefLocalesDirPath, CEF expects them to be in the folder your executable is in.
However in any case icudtl.dat must be in the same folder as the CEF library!

**Comment by xiximitho** [comment]
after do this the message :: Project raised exception class 'External: SIGABRT'.

 In file '../nptl/sysdeps/unix/sysv/linux/raise.c' at line 56

**Comment by dliw** [comment]
Sorry, right now I have no idea what could cause this.
Can you tell me, what you are trying to do? Did you try **LCLSimple** or **LCLCefClient**?

**Comment by xiximitho** [comment]
a form with chromium object, only this and i get this error.
Now i've tried the LCLCefClient and get the same :(

Felipe Mattes
Aux de programador
Fone :  +55 (49) <%2B55%20%2849%29%20%C2%A0%208898-0101>
<%2B55%20%2849%29%20%C2%A0%208898-0101>* 98411-5991*
E-mail: *mattesfelipe@gmail.com <mattesfelipe@gmail.com>*

2017-07-27 17:11 GMT-03:00 dliw <notifications@github.com>:

**Comment by dliw** [comment]
That's weird. I need more info:

1. Is there a **debug.log**? It shouldn't contain sensitive information, so you can attach it here.
2. Are you using the `Debug` or `Release` CEF library?
3. Do you get the same error with the **GTK2Minimal** example?
The tree should look like this:
```
.
├── cef_100_percent.pak
├── cef_200_percent.pak
├── cef_extensions.pak
├── cef.pak
├── devtools_resources.pak
├── icudtl.dat
├── libcef.so
├── locales
│   └── ...
├── minimal
├── natives_blob.bin
└── snapshot_blob.bin
```

4. If so: can you try to get a backtrace?
`LD_LIBRARY_PATH=. gdb --args ./minimal --renderer-cmd-prefix='xterm -title renderer -e gdb --args'`
Then type `run` in every terminal window that pops up. As soon as the error happens, type `bt`...
The browser window may stay white the first time, just reload the page.

**Comment by xiximitho** [comment]
Hey, i've solved the problem copying the files from the release folder into lazarus project folder, thank for you help.

**Comment by dliw** [comment]
Good to hear.
