### ISSUE TITLE
fpcef3 how to copy image from browser?

### ISSUE THREAD

**Issue by yunxunmi** [dliw/fpCEF3#59]
fpcef3 how to copy image from browser?

**Comment by dliw** [comment]
What do you mean by "image"? A screenshot of the web page or an image embedded into a web page?

In any case this is not specific to fpCEF, you can ask this question on the CEF forum.

**Comment by yunxunmi** [comment]
i mean an image embedded into a web page

**Comment by dliw** [comment]
Ok, so you want to get the URL of an image from the DOM?

**Comment by yunxunmi** [comment]
no, I want to copy an image to clipboard

**Comment by yunxunmi** [comment]
Has been resolved.
i open the imageUrl in a new TChromium  and use MainFrame.Copy
now it work.

thanks!

**Comment by dliw** [comment]
Ok, great! You can close this issue then.

**Comment by yunxunmi** [comment]
I
