### ISSUE TITLE
EOSError

### ISSUE THREAD

**Issue by cknyaz** [dliw/fpCEF3#60]
I'm getting an EOS Error when trying to run any program using fpCEF3, including the example programs. Any way to fix this?

Running on Ubuntu 16.04 LTS 64 bit
Lazarus version 1.6.4 x86 64 linux gtk2
FPC version 3.0.2
fpCEF3 version 3.2743 standard edition 

![image](https://user-images.githubusercontent.com/22970449/30978019-4e9ddf28-a447-11e7-80a8-67bbf601a3b4.png)

**Comment by dliw** [comment]
I guess your setup is wrong.
Please see https://github.com/dliw/fpCEF3#cef-setup

Depending on your project, the setup should look like this:
```
├── cef_100_percent.pak
├── cef_200_percent.pak
├── cef_extensions.pak
├── cef.pak
├── devtools_resources.pak
├── icudtl.dat
├── libcef.so
├── locales
│   └── ...
├── natives_blob.bin
├── simple
└── snapshot_blob.bin
```

**Comment by cknyaz** [comment]
I followed all the directions and my setup is the same, but I'm still
getting the error. It compiles fine, just doesn't run.

**Comment by cknyaz** [comment]
Ok, so I'm getting the same issue as here:
https://github.com/dliw/fpCEF3/issues/8
How was this solved?

**Comment by dliw** [comment]
AFAIR the reason for #8 was a wrong version of CEF.

Also, I would recommend to first set up fpCEF as written above and start via
```
$LD_LIBRARY_PATH=. ./simple
```
Using cef from the "global" library path is error prone, as some parts of CEF need to be in library path and some in the application folder.

**Comment by cknyaz** [comment]
Yes, I tried all that and I set a breakpoint after the LoadLibrary function and got the error that libgcrypt.so.11 cannot be opened. LoadLibrary, using the function dlopen, is able to open any other file in my system in the /usr/lib directory, except for libcef.so, It appears that this is the main issue here, that libcef.so is unable to open properly. It is trying to open  an older version of libgcrypt, which doesn't exist anymore. I, and other linux users, have the most recent, updated version of libgcrypt.so.20 version installed. Does libcef.so have a dependency on the libgcrypt.so file? I am running all of this on Virtual Box, could this be causing the error? Attached below is a screenshot of the more detailed error. 

![screenshot from 2017-10-02 15-16-03](https://user-images.githubusercontent.com/22970449/31095497-0664abb8-a787-11e7-9d63-397c223f9fa4.png)

**Comment by dliw** [comment]
Yes, with this error message it is rather clear, that libgcrypt is causing the problem.
Usually distributions allow to install both versions - 1.x and 2.x - of libgcrypt side by side.

Btw. you can check the dependencies of libcef.so via ldd.

**Comment by cknyaz** [comment]
Success! That solved the EOS error, however, I am now getting another
error: Project Simple raised exception class 'External: SIGABRT'. In file
'../sysdeps/unix/sysv/linux/raise.c' at line 54. Any ideas what could be
causing this? Thanks!

**Comment by dliw** [comment]
That's difficult. This exception could be caused by anything.

You could look into the debug log file if there are any hints or try to get a backtrace using gdb.

**Comment by cknyaz** [comment]
This is some sort of bug in the VM. Lazarus on my desktop works just fine.
