### ISSUE TITLE
Making a Screenshot with OSR?

### ISSUE THREAD

**Issue by laggyluk** [dliw/fpCEF3#61]
I need to be able to take a screenshot of page when application is minimalized. 
How do I do that? In dcef3 I'd use TBitmap but here OSR example is using OpenGL for painting.

**Comment by dliw** [comment]
With fpCEF you can use whatever canvas you want for the OSR browser.

Older versions of the OSRDemo used BGRABitmap: [code](https://github.com/dliw/fpCEF3/blob/5335a5ba437d469eb6f933e47ae0e0cd3d6e8968/Examples/OSRDemo/main.pas#L113)

**Comment by laggyluk** [comment]
Thanks!
