### ISSUE TITLE
JavaScript Invoke Problem

### ISSUE THREAD

**Issue by mercurylmy** [dliw/fpCEF3#62]
1. in the Examples/JavaScript/main.pas function ChromiumJsdialog
If not set suppressMessage := False;
Then after close the ShowMessage dialog, the whole program will stuck.

2. ExecuteJavaScript does not give a return value
After read tons of post on CEF Forum still not found a working solution for pascal. (Maybe I am just too stupid)
I need a method to run a JavaScript function and get the return value back to pascal. In sync way, this is important, please help.

Thank you very much.

**Comment by dliw** [comment]
Please always tell which version of Lazarus, Free Pascal and fpCEF on which OS you are using.

1. Sorry, I'm not sure, if I understand the problem correctly. Are you saying, that the JavaScript example without modification crashes for you?
At least on Linux I cannot reproduce this and from how I understand the CEF documentation for **on_jsdialog** there is no need to set _suppressMessage_ if the callback is executed immediately.

2. ExecuteJavaScript cannot give a return value, because JavaScript is executed in a different CEF process. Without trying I would say you need to do this:
    - Get the return value of the JavaScript function in **TMyHandler.Execute**
    - Pass the value to the main process via messages (see the DOMAccess example)

>In sync way, this is important

Because CEF uses multiple processes this is not possible. Messages are needed to communicate between the processes.

**Comment by mercurylmy** [comment]
>At least on Linux I cannot reproduce this and from how I understand the CEF documentation for on_jsdialog there is no need to set suppressMessage if the callback is executed immediately.

`ShowMessage` is not executed immediately, it wait user to close the dialog.
LCL 1.6.4, FP 3.0.2, Windows 8.1, fpCEF 3.2526 and cef 3.2526.1373.0
![a](https://user-images.githubusercontent.com/8626952/33589521-d1430d94-d9b3-11e7-950a-350f0551979b.gif)
Then it will crash after a while, same result if click the `alert(window.myval)` or `alert(cef.test.test_param)`
But if set ` suppressMessage := False;`, it will be all right.


> Because CEF uses multiple processes this is not possible. Messages are needed to communicate between the processes.

What if set `CefSingleProcess := True;`

**Comment by dliw** [comment]
Ok, I think I understand now. I will change that for the next release. The recommended way is to call the callback asynchronously anyway, so the ``ShowMessage`` in this example is a hack more or less and in no way recommended. This example is about JavaScript, so I want to keep unrelated code as minimal as possible.

``CefSingleProcess`` is not really supported by CEF. AFAIK this option is meant for developers for debugging certain aspects of CEF. You could try, but I wouldn't recommend and it is completely untested in fpCEF.

**Comment by mercurylmy** [comment]
Asynchronous? Then how to deal with this code?
```
function show_prompt() {
  var name = prompt("Please enter your name", "name")
  if (name != null && name != "") {
    alert("Hello " + name + "!");
  }
}
```

**Comment by dliw** [comment]
Please see the reference implementation [here](https://bitbucket.org/chromiumembedded/cef/src/7fe13d87c68943fcfedd07aefaffcff3647fe2a8/tests/cefclient/browser/dialog_handler_gtk.cc?at=master&fileviewer=file-view-default#dialog_handler_gtk.cc-294).

As you can see a dialog (of any type) is created and ``OnJSDialog`` returns. The dialog itself then calls the callback:

in OnJSDialog:
```
g_signal_connect(gtk_dialog_, "response", G_CALLBACK(OnDialogResponse), this);
```

in OnDialogResponse:
```
handler->js_dialog_callback_->Continue(true, GetPromptText(dialog));
```

You can do the same with fpCEF ([see here](https://github.com/dliw/fpCEF3/blob/98944b395f7eea9ed12619bfee9ac257088ea095/cef3api.pas#L2059))
```
    // Continue the JS dialog request. Set |success| to true (1) if the OK button
    // was pressed. The |user_input| value should be specified for prompt dialogs.
    cont: procedure(self: PCefJsDialogCallback; success: Integer; const user_input: PCefString); cconv;
```

**Comment by mercurylmy** [comment]
Where is `OnDialogResponse` defined?

**Comment by dliw** [comment]
It's a custom callback function in the C++ reference implementation of CEF.

With Pascal you can use whatever you see fit. You could e.g. send a message with the prompt text to the main process, handle user imput there, send the answer back and call the ``cont`` callback.
But there is certainly more than one way to do it.
