### ISSUE TITLE
cef_parse_csscolor not found? (fixed: use CEF 3.3029.1613.g22354a9)

### ISSUE THREAD

**Issue by creaothceann** [dliw/fpCEF3#63]
I get the error "Unsupported CEF library version" (would be very nice if the missing functions would be reported in the exception message). Setting a breakpoint in `cef3api`'s `CefLoadLibrary` function and stepping through the code reveals that the variable `cef_parse_csscolor` receives a NIL pointer.

**CEF:** `cef_binary_3.3029.1619.geeeb5d7_windows32.tar.bz2` from [here](http://opensource.spotify.com/cefbuilds/index.html#windows32_builds)
**compiler:** Lazarus 1.8.0, includes FPC 3.0.4
**OS:** Windows 7 (64-bit)
**files:**

    simple32.exe (from fpCEF3\Examples\LCLSimple\)
    subprocess32.exe (from fpCEF3\Examples\SubProcess\)
    natives_blob.bin
    snapshot_blob.bin
    icudtl.dat
    chrome_elf.dll
    d3dcompiler_43.dll
    d3dcompiler_47.dll
    libcef.dll
    libEGL.dll
    libGLESv2.dll
    widevinecdmadapter.dll
    cef_sandbox.lib
    libcef.lib
    cef.pak
    cef_100_percent.pak
    cef_200_percent.pak
    cef_extensions.pak
    devtools_resources.pak
    locales\am.pak ... zh-TW.pak

**Comment by dliw** [comment]
CEF 3.3029 is the correct version for the latest fpCEF, so this error should not happen.


>would be very nice if the missing functions would be reported in the exception message

Actually it would be much better to check if the CEF library is supported by comparing the version number. And this is already one of the many things I have on my TODO list.



Unfortunately due to time constrains I'm unable to support fpCEF at the moment - as much as I want to work on this library. But I hope that I will find a way to release regular updates again.

**Comment by creaothceann** [comment]
>CEF 3.3029 is the correct version for the latest fpCEF

Yeah, but right now there are ***9*** different 3.3029 versions.  
Problem fixed by using the `1613` variant. -_-'  

    05/12/2017 - CEF 3.3029.1619.geeeb5d7 / Chromium 58.0.3029.81
    05/11/2017 - CEF 3.3029.1617.gaf831b6 / Chromium 58.0.3029.81
    05/10/2017 - CEF 3.3029.1615.g753baf1 / Chromium 58.0.3029.81
    05/06/2017 - CEF 3.3029.1613.g22354a9 / Chromium 58.0.3029.81  <-- !!!!!!1
    05/05/2017 - CEF 3.3029.1612.gd81997a / Chromium 58.0.3029.81
    04/29/2017 - CEF 3.3029.1611.g44e39a8 / Chromium 58.0.3029.81
    04/28/2017 - CEF 3.3029.1609.gcb50417 / Chromium 58.0.3029.81
    04/27/2017 - CEF 3.3029.1608.g27a32db / Chromium 58.0.3029.81
    04/25/2017 - CEF 3.3029.1604.g364cd86 / Chromium 58.0.3029.81

Btw. for some reason LCLSimple only works when commenting out the `CefBrowserSubprocessPath` line in `main.pas`. Maybe I'm using the wrong settings for compiling `subprocess32.exe` or something.

**Comment by dliw** [comment]
I'm glad you could find a working version. This means CEF even breaks API compatibility within minor versions. I didn't expect this.

You have to rename `subprocess32.exe` to `subprocess.exe` or change this line:
```
CefBrowserSubprocessPath := '.' + PathDelim + 'subprocess'{$IFDEF WINDOWS}+'.exe'{$ENDIF};
```

**Comment by creaothceann** [comment]
That worked, thanks.
