### ISSUE TITLE
TChromiumOSR subprocess not loading and high CPU usage

### ISSUE THREAD

**Issue by vassilisw** [dliw/fpCEF3#64]
Hi, I'm facing the following issues with TChromiumOSR component:
1. CPU usage is reaching 100% without doing anything.
2. The subprocess is not loaded with `CefBrowserSubprocessPath := '.' + PathDelim + 'subprocess'...;` I'm checking the processes names via htop (linux) and task manager (in windows).

**Reproduce:** On a _new_ project's form just place a TChromiumOSR component. On FormCreate paste: `CefBrowserSubprocessPath := '.' + PathDelim + 'subprocess'{$IFDEF WINDOWS}+'.exe'{$ENDIF};`. Run the project and you will see high (98+%) CPU and no subprocess in use (htop or task manager)

_P.S._
_The TChromium components works just fine though._
_Of course the subprocess executable exists._

**Tested with:**
linux mint 17.2 64bit  - Lazarus 1.6
	fpCEF3 3.2743 CPU works ok, subprocess not working

linux mint 17.3 64bit - Lazarus 1.6.4
	fpCEF3 3.3029 CPU is high, subprocess not working

windows 7 32 bit - Lazarus 1.6.4
	fpCEF3 3.3029 CPU is high, subprocess not working

Thank you...

**Comment by dliw** [comment]
It seems, that setting `CefBrowserSubprocessPath` in `FormCreate` for `TChromiumOSR` is too late. It must be done in the `Initialization` section.

If I modify the OSRDemo accordingly, the subprocess is used and works just fine.

One more bug to fix. Unfortunately due to time constrains I'm unable to work on fpCEF at the moment ...

**Comment by vassilisw** [comment]
Indeed subprocess works fine if set in `initialization` section!
Any ideas what might be causing the high cpu usage when `TChromiumOSR` is used? I might be able to find a workaround with a little help.

Thank you very much for the reply.

**Comment by dliw** [comment]
Do you also see high CPU usage with the `OSRDemo` example? For me on Linux the CPU usage for this demo is almost zero.
I cannot think of an obvious cause for your high CPU load. You will probably need to profile your code.

**Comment by vassilisw** [comment]
Same thing with `OSRDemo`, as with just dropping a `TChromiumOSR` component on an empty project's form. Weird...
