### ISSUE TITLE
Problem running under Linux OS

### ISSUE THREAD

**Issue by alpiki** [dliw/fpCEF3#72]
Hi;
I am using Lazarus 1.8.2 and fpc 3.0.4 in Lubuntu 18.04 operating system. (all 64bit)
The fpCEF3 version number is V3.3029. I have successfully compiled the LCLSimple sample application under Examples and then tested it with the CEF binaries.

I noticed the binary files cef_binary_3.3029.1619.geeeb5d7_linux64_client and the cefsimple application works well.

But unfortunately I could not run directly or under the commandline (without debug lazarus) the sample application with the following error message.

Error Message:
An operating system call failed.
Press OK to ignore and risk data corruption.
Press Abort to kill the program.

Best regards.

**Comment by temaps** [comment]
Move file libcef.so from your project folder to /usr/lib64

**Comment by alpiki** [comment]
Hi;
it works. Thank you.
Best regards.
