### ISSUE TITLE
Question - Project Descontinued?

### ISSUE THREAD

**Issue by kholyphoenix1** [dliw/fpCEF3#77]
Hello, I can not use current versions of Chromium for lack of Components update.
I would like to know if the project has been discontinued.

Congratulations on the project!

Thanks!

**Comment by dliw** [comment]
Hello, I have not completely abandoned the project, but it has very low priority to me. While working on the update for CEF 3.3538 (development branch) I had to realize, that the LCL integration on Linux (and very likely on Mac, too) is fundamentally broken and CEF does not behave as it used to. I have not found a way to solve this problem. Things work on Windows, but there already is CEF4Delphi, which seems to do a good job and also works with Lazarus, so I see no point in keeping fpCEF up to date.

**Comment by kholyphoenix1** [comment]
No Problem.
Thanks for help!
