### ISSUE TITLE
why CEF version same with Chromium version in http://opensource.spotify.com/cefbuilds/index.html?

### ISSUE THREAD

**Issue by TangMonk** [dliw/fpCEF3#78]
I cannot found verions like v3.3029 in the http://opensource.spotify.com/cefbuilds/index.html page.

**Comment by dliw** [comment]
Type ``3.3029`` into the version filter input box. The download links should show up then.

**Comment by TangMonk** [comment]
> Type `3.3029` into the version filter input box. The download links should show up then.

seems after 03/14/2019, the CEF change the version strategy
